import '../scss/registration.scss';
import '../pages/registration/index.pug';
import '../fonts/Montserrat-Black.woff2';
import '../fonts/Montserrat-Bold.woff2';
import '../img/svg/header-logo.svg';
import '../img/svg/instagram.svg';
import '../img/svg/twitter.svg';
import '../img/svg/facebook.svg';
import '../img/bg.jpg';
import './ibg.js'