import '../pages/room_details/index.pug';
import '../scss/room_details.scss';
import './ibg.js'
import './piechart.js'
import '../img/room_details/svg/fire.svg';
import '../img/room_details/svg/home.svg';
import '../img/room_details/svg/smail.svg';
import '../img/room_details/bg_1.jpg';
import '../img/room_details/bg_2.jpg';
import '../img/room_details/bg_3.jpg';
import '../img/room_details/reviews/girl.jpg';
import '../img/room_details/reviews/man.jpg';
import '../img/room_details/reviews/favorite_border.svg';
import '../img/room_details/reviews/favorite.svg';
import '../img/room_details/reviews/more-detailed.svg';
